steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/remote-builder-prd', '.' ]
images:
- 'gcr.io/$PROJECT_ID/remote-builder-prd'
tags: ['cloud-builders-community']
steps:
- name: gcr.io/$PROJECT_ID/remote-builder-prd
  env:
    - COMMAND=ls -la

